# # ==============================================================================
# # FILE LOCATION: Dynamic_Scorecard_System/dynamic_engine.py
# # ==============================================================================

import pandas as pd
import numpy as np
import json
import os
import sys
import importlib.util
import time
import tkinter as tk
from tkinter import filedialog, messagebox
import threading
from concurrent.futures import ThreadPoolExecutor

def prompt_file(title="Select File"):
    """
    A special function injected into the Python sandbox. 
    It pauses execution and prompts the user to select a file using a native OS window.
    """
    root = tk.Tk()
    root.withdraw() # Hide the main tk window
    root.attributes('-topmost', True) # Force to front
    file_path = filedialog.askopenfilename(title=title, filetypes=[("Excel/CSV files", "*.xlsx *.csv"), ("All files", "*.*")])
    root.destroy()
    return file_path

def confirm_choice(title, message):
    """Prompts the user with a Yes/No dialog."""
    root = tk.Tk()
    root.withdraw()
    root.attributes('-topmost', True)
    result = messagebox.askyesno(title, message)
    root.destroy()
    return result

class OmniEvaluator:
    """Handles parsing and executing raw Python in a multi-dataframe environment."""
    
    @staticmethod
    def execute_python_logic(dfs_dict, vars_dict, code_block, script_path=None):
        # Load all dataframes, variables, and our special prompt function into the environment
        local_env = {**dfs_dict, **vars_dict, 'np': np, 'pd': pd, 'os': os, 'sys': sys, 'prompt_file': prompt_file}
        
        # FIX: Inject standard dunder variables so external Tkinter scripts can initialize properly
        local_env['__name__'] = '__main__'
        if script_path:
            local_env['__file__'] = script_path
        else:
            local_env['__file__'] = '<string>'
            
        try:
            # Pass local_env as BOTH globals and locals so functions can see imported modules like 'tk'
            exec(code_block, local_env, local_env)
            
            # Extract out the DataFrames (including those generated by external tkinter scripts)
            updated_dfs = {k: v for k, v in local_env.items() if isinstance(v, pd.DataFrame)}
            
            # Extract out the variables for debugging
            updated_vars = {}
            for k, v in local_env.items():
                if not isinstance(v, pd.DataFrame) and not callable(v) and not k.startswith('_') and str(type(v).__module__) == 'builtins':
                    updated_vars[k] = v
                        
            return updated_dfs, updated_vars
        except Exception as e:
            raise RuntimeError(f"Python Logic Error in block:\n{code_block}\nError: {str(e)}")

try:
    import xlwings as xw
except ImportError:
    xw = None

class ExcelFormulaEngine:
    """Uses a background Excel instance to evaluate 100% of native Excel formulas."""
    
    @staticmethod
    def evaluate(dfs_dict, formula, target_alias, target_col=None):
        if xw is None:
            raise ImportError("xlwings is required for Excel Formula support. Please run 'pip install xlwings'.")
            
        # Optimization: Identify which DataFrames are actually needed
        referenced_names = []
        for name in dfs_dict.keys():
            if f"{name}!" in formula or f"'{name}'!" in formula:
                referenced_names.append(name)
        
        if target_col and target_alias in dfs_dict and target_alias not in referenced_names:
            referenced_names.append(target_alias)
            
        if not referenced_names and target_alias in dfs_dict:
            referenced_names.append(target_alias)
            
        if not referenced_names:
            referenced_names = list(dfs_dict.keys())

        print(f" -> Calculation Engine: Loading {len(referenced_names)} relevant DataFrames into Excel...")

        app = xw.App(visible=False, add_book=False)
        try:
            wb = app.books.add()
            existing_sheet_names = [s.name for s in wb.sheets]
            
            for name in referenced_names:
                df = dfs_dict[name]
                if df is None or (isinstance(df, pd.DataFrame) and df.empty):
                    continue
                
                safe_name = str(name)[:31]
                for char in r"[]:*?/\ ":
                    safe_name = safe_name.replace(char, "_")
                if not safe_name or safe_name.isspace():
                    safe_name = f"Sheet_{len(existing_sheet_names)}"
                
                if safe_name in existing_sheet_names:
                    sheet = wb.sheets[safe_name]
                else:
                    sheet = wb.sheets.add(name=safe_name)
                    existing_sheet_names.append(safe_name)
                
                try:
                    clean_df = df.copy()
                    rows, cols = clean_df.shape
                    if rows > 1048575: clean_df = clean_df.iloc[:1048575]
                    if cols > 16384: clean_df = clean_df.iloc[:, :16384]
                        
                    for col in clean_df.select_dtypes(include=[np.number]).columns:
                        clean_df[col] = clean_df[col].replace([np.inf, -np.inf], np.nan)
                    
                    for col in clean_df.select_dtypes(include=['object']).columns:
                        clean_df[col] = clean_df[col].astype(str).str.replace(r'[\x00-\x1f\x7f-\x9f]', '', regex=True)
                    
                    sheet.range('A1').options(index=False).value = clean_df
                except Exception as write_err:
                    print(f"    [!] Warning: High-speed write failed for '{name}', trying safe fallback...")
                    try:
                        sheet.range('A1').value = df.astype(str).values.tolist()
                    except:
                        print(f"    [!!] Critical: Could not load '{name}' into calculation engine.")
                
            calc_sheet = wb.sheets.add(name="CALC_ENGINE")
            
            if target_col and target_alias in dfs_dict:
                row_count = len(dfs_dict[target_alias])
                if row_count > 0:
                    first_cell = calc_sheet.range('A1')
                    first_cell.formula = formula
                    
                    if row_count > 1:
                        fill_range = calc_sheet.range(f'A1:A{row_count}')
                        first_cell.api.AutoFill(fill_range.api, 0)
                    
                    wb.app.calculate()
                    col_results = calc_sheet.range(f'A1:A{row_count}').value
                    if not isinstance(col_results, list): col_results = [col_results]
                    dfs_dict[target_alias][target_col] = col_results
                return dfs_dict
            else:
                calc_sheet.range('A1').formula = formula
                wb.app.calculate()
                result = calc_sheet.range('A1').options(pd.DataFrame, index=False, header=True).value
                if not isinstance(result, pd.DataFrame):
                    result = pd.DataFrame({target_alias: [result]})
                dfs_dict[target_alias] = result
                return dfs_dict
            
        finally:
            try:
                wb.close()
                app.quit()
            except:
                pass

class DynamicPipelineEngine:
    def __init__(self, config_path=None):
        self.config = {}
        self.runtime_file_cache = {} 
        self.parsed_excel_cache = {} 
        self.cache_lock = threading.Lock()
        if config_path:
            with open(config_path, 'r') as f:
                self.config = json.load(f)
            
    def _apply_step(self, dfs_dict, vars_dict, step):
        """Applies a single macro step to the state."""
        if not hasattr(self, 'runtime_file_cache'): self.runtime_file_cache = {}
        if not hasattr(self, 'parsed_excel_cache'): self.parsed_excel_cache = {}
        if not hasattr(self, 'cache_lock'): self.cache_lock = threading.Lock()

        action = step.get('action')
        params = step.get('params', {})

        if action == "load_file":
            filepath = params.get('filepath')
            sheet = params.get('sheet', 0)
            header = params.get('header', 0)
            alias = params.get('alias')
            prompt_at_runtime = params.get('prompt_at_runtime', False)
            
            if not prompt_at_runtime and filepath and not os.path.exists(filepath):
                print(f" -> [!] Warning: Path not found: {filepath}")
                prompt_at_runtime = True

            if prompt_at_runtime:
                with self.cache_lock:
                    cached_path = self.runtime_file_cache.get(filepath)
                
                if cached_path:
                    filepath = cached_path
                    print(f"Auto-using previously selected file for '{alias}': {filepath}")
                else:
                    print(f"Waiting for user to select file for '{alias}'...")
                    new_filepath = prompt_file(f"Please select the data file for '{alias}' (Original: {os.path.basename(filepath)})")
                    if not new_filepath:
                        raise FileNotFoundError(f"Execution aborted: User did not select a file for '{alias}'.")
                    with self.cache_lock:
                        self.runtime_file_cache[filepath] = new_filepath
                    filepath = new_filepath
            
            print(f"Loading data into '{alias}' from {filepath}...")
            if filepath.endswith('.csv'):
                dfs_dict[alias] = pd.read_csv(filepath, header=header)
            else:
                try:
                    with self.cache_lock:
                        if filepath not in self.parsed_excel_cache:
                            self.parsed_excel_cache[filepath] = pd.ExcelFile(filepath)
                        xl = self.parsed_excel_cache[filepath]
                    
                    try:
                        dfs_dict[alias] = pd.read_excel(xl, sheet_name=sheet, header=header)
                    except ValueError:
                        print(f"Warning: Sheet '{sheet}' not found. Loading first sheet.")
                        dfs_dict[alias] = pd.read_excel(xl, sheet_name=0, header=header)
                except Exception as e:
                    print(f"Error loading Excel file: {e}")
                    raise

        elif action == "load_all_sheets":
            filepath = params.get('filepath')
            header = params.get('header', 0)
            prompt_at_runtime = params.get('prompt_at_runtime', False)
            
            if not prompt_at_runtime and filepath and not os.path.exists(filepath):
                print(f" -> [!] Warning: Path not found: {filepath}")
                prompt_at_runtime = True

            if prompt_at_runtime:
                with self.cache_lock:
                    cached_path = self.runtime_file_cache.get(filepath)
                
                if cached_path:
                    filepath = cached_path
                else:
                    use_existing = False
                    if filepath and os.path.exists(filepath):
                        use_existing = confirm_choice("Use Configured File?", 
                            f"A file exists at the configured path:\n{filepath}\n\nDo you want to USE THIS file?")

                    if use_existing:
                        print(f" -> Using existing file: {filepath}")
                    else:
                        new_filepath = prompt_file(f"Select Excel file to load ALL sheets (Original: {os.path.basename(filepath)})")
                        if not new_filepath:
                            raise FileNotFoundError(f"Execution aborted: User did not select a file.")
                        with self.cache_lock:
                            self.runtime_file_cache[filepath] = new_filepath
                        filepath = new_filepath

            print(f"Parallel Loading ALL sheets from {filepath}...")
            try:
                with self.cache_lock:
                    if filepath not in self.parsed_excel_cache:
                        self.parsed_excel_cache[filepath] = pd.ExcelFile(filepath)
                    xl = self.parsed_excel_cache[filepath]
                
                sheet_names = xl.sheet_names
                
                def load_sheet(s_name):
                    print(f" -> Thread Ingest: '{s_name}'")
                    return s_name, pd.read_excel(xl, sheet_name=s_name, header=header)

                with ThreadPoolExecutor() as executor:
                    results = list(executor.map(load_sheet, sheet_names))
                
                for name, df in results:
                    dfs_dict[name] = df
                    
            except Exception as e:
                print(f"Error batch loading Excel file: {e}")
                raise

        elif action == "map_columns":
            target_alias = params.get('target_df')
            source_alias = params.get('source_df')
            target_key = params.get('target_key')
            source_key = params.get('source_key')
            cols_to_map = params.get('columns_to_map', [])
            how = params.get('how', 'left')

            if target_alias not in dfs_dict or source_alias not in dfs_dict:
                raise ValueError(f"One or both DataFrames ('{target_alias}', '{source_alias}') not found.")
            
            target_df = dfs_dict[target_alias]
            source_df = dfs_dict[source_alias]

            if target_key not in target_df.columns or source_key not in source_df.columns:
                raise ValueError(f"Keys not found in DataFrames.")

            valid_cols = [c for c in cols_to_map if c in source_df.columns]
            if not valid_cols: return

            source_subset = source_df[[source_key] + valid_cols].drop_duplicates(subset=[source_key])
            merged = target_df.merge(source_subset, left_on=target_key, right_on=source_key, how=how, suffixes=('', '_map_temp'))

            if target_key != source_key and source_key in merged.columns:
                merged = merged.drop(columns=[source_key])
            
            temp_cols = [c for c in merged.columns if c.endswith('_map_temp')]
            if temp_cols: merged = merged.drop(columns=temp_cols)

            dfs_dict[target_alias] = merged

        elif action == "execute_python_logic":
            code = params.get('code_block', '')
            dfs_dict, vars_dict = OmniEvaluator.execute_python_logic(dfs_dict, vars_dict, code)

        elif action == "evaluate_excel_formula":
            formula = params.get('formula', '')
            target = params.get('target_alias', 'Calculated_Result')
            target_col = params.get('target_col')
            dfs_dict = ExcelFormulaEngine.evaluate(dfs_dict, formula, target, target_col=target_col)

        elif action == "run_python_file":
            script_path = params.get('script_path')
            if os.path.exists(script_path):
                with open(script_path, 'r', encoding='utf-8') as f: code = f.read()
                dfs_dict, vars_dict = OmniEvaluator.execute_python_logic(dfs_dict, vars_dict, code, script_path=script_path)
            else:
                raise FileNotFoundError(f"Script file not found: {script_path}")

        elif action == "human_intervention_required":
            msg = params.get('message', 'Manual intervention required.')
            raise RuntimeError(f"Pipeline Halted: {msg}")

        return dfs_dict, vars_dict

    def run_pipeline(self):
        """Main execution flow for headless mode."""
        start_time = time.time()
        print(f"[{time.strftime('%H:%M:%S')}] Starting Execution...")
        
        dfs_dict = {}
        vars_dict = {}
        processes = self.config.get('processes', {})
        export_list = self.config.get('export_dfs')
        
        for process_name, steps in processes.items():
            print(f"\n--- Starting Process: {process_name} ---")
            for step in steps:
                dfs_dict, vars_dict = self._apply_step(dfs_dict, vars_dict, step)

        os.makedirs('Data_Output', exist_ok=True)
        output_file = os.path.join('Data_Output', 'Final_Pipeline_Output.xlsx')
        
        with pd.ExcelWriter(output_file) as writer:
            exported_count = 0
            for alias, df in dfs_dict.items():
                if export_list is None or alias in export_list:
                    df.to_excel(writer, sheet_name=str(alias)[:31], index=False)
                    exported_count += 1
            if exported_count == 0:
                pd.DataFrame({"Status": ["No data exported."]}).to_excel(writer, sheet_name="Empty", index=False)
                
        elapsed = time.time() - start_time
        print(f"Pipeline Complete! Time: {elapsed:.2f} seconds.")
